{
 "title": "Squid Sample Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "content": "<h1><center>Squid Sample Dashboard</center></h1>"
  },
  {
   "title": "Services Up",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "up{job='squid'}" }
   ]
  },
  {
   "title": "Bytes Hit Rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "squid_client_http_hit_kbytes_out_bytes_total / squid_client_http_kbytes_out_kbytes_total"
    }
   ]
  },
  {
   "title": "Catch Hit Rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "squid_client_http_hits_total / squid_client_http_requests_total",
     "legendFormat": "Hit rate"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "squid_client_http_errors_total / squid_client_http_requests_total"
    }
   ]
  },
  {
   "title": "Client Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "squid_client_http_requests_total",
     "legendFormat": "Total Requests"
    },
    { "expr": "squid_client_http_hits_total", "legendFormat": "Total HTTP hits" },
    { "expr": "squid_client_http_errors_total", "legendFormat": "Total Errors" }
   ]
  },
  {
   "title": "Client Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "squid_client_http_kbytes_in_kbytes_total * -1",
     "legendFormat": "HTTP Traffic in"
    },
    {
     "expr": "squid_client_http_kbytes_out_kbytes_total",
     "legendFormat": "HTTP Traffic Out"
    },
    {
     "expr": "squid_client_http_hit_kbytes_out_bytes_total",
     "legendFormat": "HTTP Traffic Out Hits"
    }
   ]
  }
 ]
}