name: Docker Image CI

on:
  push:
    branches: [master]
    tags: ['v*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      id: login
      uses: docker/login-action@v3
      continue-on-error: true
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push the Docker image latest
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ steps.login.outcome == 'success' }}
        tags: ${{ secrets.DOCKER_USERNAME || 'local' }}/squid-exporter:latest,${{ startsWith(github.ref, 'refs/tags/v') && env.rev_tag || '' }}
        platforms: linux/i386,linux/amd64,linux/arm64,linux/arm/v7
      env:
        rev_tag: ${{ secrets.DOCKER_USERNAME }}/squid-exporter:${{ github.ref_name }} # Construct tag as env var to make tags line easier to read.
