name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Go environment
      uses: actions/setup-go@v4.0.0
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges.
        go-version: 1.20.3
        # Path to the go.mod or go.work file.
        go-version-file: go.mod
    - uses: actions/checkout@v3

    - name: Build
      run: make
